spring:
    profiles:
        include:
            - local, prod
        active: local
    batch:
      job:
        enabled: true
        names: ${job.name:NONE}
    main:
      allow-bean-definition-overriding: true
            
server:
  port: 18080